### ISSUE TITLE
Google ask permission each time when try to login.

### ISSUE THREAD

**Issue by mxly08** [kettari/authgoogle#16]
Thanks for the great extension. :)

I have an issue and can't find ways to resolve. Google keeps asking permission to "Have offline access access" each time when users try to login the system. Is there any way to deal with that? Thanks.

**Comment by daniviga** [comment]
I solved adding:
```php
        $client->setAccessType('online');
        $client->setApprovalPrompt('auto');
```
here https://github.com/kettari/authgoogle/blob/master/auth.php#L78

**Comment by kettari** [comment]
@daniviga thanx!
