### ISSUE TITLE
Hide plain auth login form

### ISSUE THREAD

**Issue by billsinc** [kettari/authgoogle#31]
It would be nice to have the option of hiding the plain auth login fields when Google auth is enabled.  I see users trying to enter their Google credentials in the plain auth fields.

**Comment by rickard-505** [comment]
I agree, bump !

**Comment by wpg4665** [comment]
My 2 cents....by adding CSS in a custom dokuwiki/conf/userstyles.css, you can easily apply

`#dw__login {
  display: none;
}`

This allows "power users" to still have access to plain auth if necessary, while keep "dumb users" from putting credentials into the plain auth form. Maybe not a fix, but a great workaround that doesn't require futzing with Dokuwiki core files

**Comment by billsinc** [comment]
Thanks @wpg4665 this works great.
