### ISSUE TITLE
Auth Google Error: access denied for xxx@gmail.com

### ISSUE THREAD

**Issue by rickard-505** [kettari/authgoogle#33]
Iam getting this error, (tried with multiple accounts) - where can I find more info on what goes wrong? logs?

(after following the setup guide)

**Comment by kettari** [comment]
Hi Rickard,

Probably you have to set allowed domains in the AuthGoogle settings. Please check "Allowed email domains" option in the admin settings of your dokuwiki.

Pls check docs (here: https://www.dokuwiki.org/plugin:authgoogle#configuration_and_settings):

> **Allowed email domains:** allowed email addresses and/or domains, separated by space. You can allow only certain domains to be used as authentication provider. For example, corporation “Example” has Google Apps for Business and wants only corporate users to login; also allow CEO to use his home email: “\*@example.com ceo_home_example@gmail.com”. Default: “\*” (all domains, all addresses).

**Comment by rickard-505** [comment]
thanks - it was just crappy user config....... thanks for input !

**Comment by kettari** [comment]
;)
