### ISSUE TITLE
BUG: Register declaration change required to remove error in DokuWiki

### ISSUE THREAD

**Issue by Rvice** [kettari/authgoogle#42]
Dokuwiki Release 2017-02-19b "Frusterick Manners"

Similar to issue:
https://github.com/kettari/authgoogle/issues/38

Modify action.pho in the authgoogle folder with the following line change:

Change:
function register(&$controller)

to:
function register(Doku_Event_Handler $controller)

**Comment by kettari** [comment]
Hi,

Could you please propose pull request? I will merge it.

**Comment by Rvice** [comment]
Kettari, Done see Pull Request 45
https://github.com/kettari/authgoogle/pull/45

**Comment by kettari** [comment]
Merged.
